# Generated by Django 3.1.2 on 2020-10-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapis', '0002_useraccountmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplaidmaster',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
