# Generated by Django 3.1.2 on 2020-10-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapis', '0003_userplaidmaster_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaidmaster',
            name='item_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.CreateModel(
            name='UserTransactionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.CharField(max_length=128)),
                ('account_owner', models.CharField(max_length=128, null=True)),
                ('transaction_id', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('name', models.CharField(max_length=128)),
                ('merchant_name', models.CharField(max_length=128, null=True)),
                ('category_id', models.IntegerField()),
                ('category', models.JSONField(null=True)),
                ('iso_currency_code', models.CharField(max_length=128, null=True)),
                ('unofficial_currency_code', models.CharField(max_length=128, null=True)),
                ('location', models.JSONField()),
                ('payment_channel', models.CharField(max_length=128)),
                ('pending', models.BooleanField(default=True)),
                ('payment_meta', models.JSONField()),
                ('user_account_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plaidapis.useraccountmaster')),
                ('user_plaid_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plaidapis.userplaidmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
