# Generated by Django 3.1.2 on 2020-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapis', '0004_auto_20201026_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookCallbackLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
