# Generated by Django 3.1.2 on 2020-10-26 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapis', '0005_webhookcallbacklogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactionmaster',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertransactionmaster',
            name='authorized_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertransactionmaster',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertransactionmaster',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='usertransactionmaster',
            name='user_account_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='plaidapis.useraccountmaster'),
        ),
    ]
