# Generated by Django 3.1.2 on 2020-10-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapis', '0006_auto_20201026_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactionmaster',
            name='authorized_date',
            field=models.DateField(null=True),
        ),
    ]
