# Generated by Django 3.1.2 on 2020-10-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaidapis', '0007_auto_20201026_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountmaster',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
